# Generated by Django 4.0.5 on 2022-06-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_osoba_pesel_alter_osoba_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wybory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('typ', models.CharField(choices=[('prezydenckie', 'Prezydenckie'), ('parlamentarne', 'Parlamentarne'), ('starosty', 'Starosty roku'), ('dziekana', 'Dziekana wydziału')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Uprawnieni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CzyZaglosowal', models.BooleanField(default=False)),
                ('id_wyborow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wybory')),
                ('pesel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.osoba')),
            ],
        ),
        migrations.CreateModel(
            name='Kandydaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poparcie', models.PositiveSmallIntegerField()),
                ('id_wyborow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wybory')),
                ('pesel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.osoba')),
            ],
        ),
    ]
