# Generated by Django 4.0.5 on 2022-06-09 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wybory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('typ', models.CharField(choices=[('prezydenckie', 'Prezydenckie'), ('parlamentarne', 'Parlamentarne'), ('starosty', 'Starosty roku'), ('dziekana', 'Dziekana wydziału')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Wybory',
            },
        ),
        migrations.CreateModel(
            name='Uprawnieni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CzyZaglosowal', models.BooleanField(default=False)),
                ('id_wyborow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.wybory')),
                ('pesel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Uprawnieni',
            },
        ),
        migrations.CreateModel(
            name='Kandydaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poparcie', models.PositiveSmallIntegerField(default=0)),
                ('id_wyborow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.wybory')),
                ('pesel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kandydaci',
            },
        ),
    ]
