# Generated by Django 4.0.5 on 2022-06-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypWyborow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='wybory',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.typwyborow'),
        ),
    ]
