# Generated by Django 4.0.5 on 2022-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_wybory_czy_aktywne_wybory_data_rozpoczecia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typwyborow',
            name='typ',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
